-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.my_contacts;

CREATE TABLE IF NOT EXISTS public.my_contacts
(
    contact_id bigserial,
    first_name character varying(30),
    last_name character varying(30),
    phone character varying(10),
    email character varying(100),
    gender character varying(1),
    birthday date,
    prof_id integer,
    zip_code character varying(4),
    status_id smallint,
    PRIMARY KEY (contact_id)
);

DROP TABLE IF EXISTS public.profession;

CREATE TABLE IF NOT EXISTS public.profession
(
    prof_id bigserial,
    profession character varying(50),
    PRIMARY KEY (prof_id),
    UNIQUE (profession)
);

DROP TABLE IF EXISTS public.zip_code;

CREATE TABLE IF NOT EXISTS public.zip_code
(
    zip_code character varying(4),
    city character varying(30),
    province character varying(30),
    PRIMARY KEY (zip_code)
);

DROP TABLE IF EXISTS public.status;

CREATE TABLE IF NOT EXISTS public.status
(
    status_id bigserial,
    status character varying(20),
    PRIMARY KEY (status_id)
);

DROP TABLE IF EXISTS public.contact_interest;

CREATE TABLE IF NOT EXISTS public.contact_interest
(
    contact_id smallint,
    interest_id smallint
);

DROP TABLE IF EXISTS public.contact_seeking;

CREATE TABLE IF NOT EXISTS public.contact_seeking
(
    contact_id smallint,
    seeking_id smallint
);

DROP TABLE IF EXISTS public.interests;

CREATE TABLE IF NOT EXISTS public.interests
(
    interest_id bigserial,
    interest character varying(50),
    PRIMARY KEY (interest_id)
);

DROP TABLE IF EXISTS public.seeking;

CREATE TABLE IF NOT EXISTS public.seeking
(
    seeking_id bigserial,
    seeking character varying(50),
    PRIMARY KEY (seeking_id)
);

ALTER TABLE IF EXISTS public.my_contacts
    ADD FOREIGN KEY (prof_id)
    REFERENCES public.profession (prof_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.my_contacts
    ADD FOREIGN KEY (zip_code)
    REFERENCES public.zip_code (zip_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.my_contacts
    ADD FOREIGN KEY (status_id)
    REFERENCES public.status (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_interest
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.my_contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_interest
    ADD FOREIGN KEY (interest_id)
    REFERENCES public.interests (interest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_seeking
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.my_contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_seeking
    ADD FOREIGN KEY (seeking_id)
    REFERENCES public.seeking (seeking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

-- Insert contacts into my_contacts table --
INSERT INTO my_contacts (
	first_name,
    last_name,
    phone, -- 10 digits --
    email,
    gender, -- M, F, or O --
    birthday, -- yyyy/mm/dd --
    prof_id, -- 1 to 9 --
    zip_code, -- 4 digits --
    status_id -- 1 for single, 2 for married --
)
VALUES
	('John', 'Doe', '0847671284', 'johndoe@gmail.com', 'M', '1966/3/24', 1, 9301, 1),
	('Jane', 'Smith', '0836296341', 'janesmith@gmail.com', 'F', '1976/4/13', 2, 9420, 2),
	('Max', 'Anderson', '0847671284', 'maxanderson@gmail.com', 'O', '1998/6/26', 3, 6011, 1),
	('Gary', 'James', '0847671284', 'garyjames@gmail.com', 'M', '1976/10/16', 5, 9301, 1),
	('Irene', 'Klein', '0847671284', 'ireneklein@gmail.com', 'F', '2000/7/18', 2, 1211, 2),
	('Jesse', 'Faden', '0847671284', 'jessefaden@gmail.com', 'O', '1989/8/25', 4, 6011, 2),
	('Logan', 'Dory', '0847671284', 'logandory@gmail.com', 'M', '1996/2/19', 6, 9301, 1),
	('Dylon', 'Sharpe', '0847671284', 'dylonsharpe@gmail.com', 'F', '1982/7/22', 9, 1732, 2),
	('David', 'Glenn', '0847671284', 'davidglenn@gmail.com', 'M', '1976/1/23', 2, 0699, 1),
	('Veronica', 'Howler', '0847671284', 'veronicahowler@gmail.com', 'F', '1991/4/14', 6, 8315, 1),
	('Francis', 'Kyle', '0847671284', 'fronciskyle@gmail.com', 'M', '1997/6/17', 4, 5605, 2),
	('Harry', 'Vernon', '0847671284', 'harryvernon@gmail.com', 'M', '1968/4/25', 6, 2092, 1),
	('Peter', 'Dove', '0847671284', 'poterdove@gmail.com', 'M', '1979/8/21', 5, 2999, 2),
	('Christina', 'Zepinski', '0847671284', 'christinazepinski@gmail.com', 'F', '1972/10/22', 1, 1380, 1),
	('Elanore', 'Skorsky', '0847671284', 'elanoreskorsky@gmail.com', 'F', '1995/11/29', 3, 2735, 1),
	('Gillian', 'Oliver', '0847671284', 'gillianoliver@gmail.com', 'F', '1989/12/24', 9, 4024, 1),
	('Douglas', 'Fisher', '0847671284', 'douglasfisher@gmail.com', 'M', '1982/9/30', 8, 8375, 2),
	('Catherine', 'Elman', '0847671284', 'catherineelman@gmail.com', 'F', '1981/5/26', 4, 2999, 2),
	('Garret', 'Fring', '0847671284', 'garretfring@gmail.com', 'M', '1985/2/27', 7, 5605, 1),
	('Curtis', 'Conner', '0847671284', 'curtisconner@gmail.com', 'M', '1960/7/14', 1, 3201, 2);
	
-- test constraints --
INSERT INTO my_contacts (
	first_name,
    last_name,
    phone,
    email,
    gender,
    birthday,
    prof_id,
    zip_code,
    status_id
)
VALUES
	('John', 'Doe', '0847671284', 'johndoe@gmail.com', 'M', '1966/3/24', 1, 12345, 1);
	
	
-- populating profession table with professions --	
INSERT INTO profession (
    profession
)
VALUES
	('Risk Management'),
	('Web Developer'),
	('Digital Marketing'),
	('Writer'),
	('Construction Worker'),
	('Architect'),
	('Engineer'),
	('Dentist'),
	('Doctor');
	
	
-- populate zip_code table with zip codes, cities, and provinces --
INSERT INTO zip_code (
	zip_code,
    city,
    province
)
VALUES 
	(5605, 'Bhisho', 'Eastern Cape'),
	(9301, 'Bloemfontein', 'Free State'),
	(2092, 'Johannesburg', 'Gauteng'),
	(3201, 'Pietermaritzburg', 'KwaZulu-Natal'),
	(0699, 'Polokwane', 'Limpopo'),
	(1211, 'Mbombela', 'Mpumalanga'),
	(2735, 'Mahikeng', 'North West'),
	(8315, 'Kimberley', 'Northern Cape'),
	(7550, 'Cape Town', 'Western Cape'),
	(6011, 'Gqeberha', 'Eastern Cape'),
	(9420, 'Winburg', 'Free State'),
	(1732, 'Krugersdorp', 'Gauteng'),
	(4024, 'Durban', 'KwaZulu-Natal'),
	(1380, 'Hoedspruit', 'Limpopo'),
	(1123, 'Lydenburg', 'Mpumalanga'),
	(2999, 'Rustenburg', 'North West'),
	(8375, 'Barkley West', 'Northern Cape'),
	(7624, 'Paarl', 'Western Cape');
	
-- test constraints --
INSERT INTO zip_code (
	zip_code,
    city,
    province
)
VALUES
	(12345, 'City', 'Province');
	
	
-- populate the status table --
INSERT INTO status (
	status
)
VALUES 
	('Single'),
	('Married');
	
	
-- populate the interests table --	
INSERT INTO interests (
	interest
)
VALUES
	('Fishing'),
	('Hiking'),
	('Knitting'),
	('Reading'),
	('Gardening'),
	('Painting'),
	('Movies'),
	('Series'),
	('Gaming'),
	('Cooking');
	
	
-- populate contact_interest table --
INSERT INTO contact_interest (
	contact_id, -- 1 to 20 --
	interest_id -- 1 to 10 --
)
VALUES
	(1, 3),(1, 4),(2, 1),(2, 8),(3, 3),(3, 7),(4, 5),(4, 9),(5, 8),(5, 1),
	(6, 2),(6, 3),(7, 5),(7, 6),(8, 9),(8, 6),(9, 7),(9, 8),(10, 1),(10, 2),
	(11, 7),(11, 9),(12, 4),(12, 6),(13, 3),(13, 4),(14, 6),(14, 8),(15, 3),(15, 4),
	(16, 5),(16, 1),(17, 3),(17, 7),(18, 2),(18, 8),(19, 3),(19, 9),(20, 5),(20, 7);
	
	
-- populate the seeking table --
INSERT INTO seeking (
	seeking
)
VALUES 
	('Long-term'),
	('Short-term'),
	('Marraige'),
	('Companionship'),
	('Experimenting');
	
	
-- populate the contact_seeking table
INSERT INTO contact_seeking (
	contact_id, -- 1 to 20 --
	seeking_id -- 1 to 5 --
)
VALUES
	(1, 2),(2, 1),(3, 5),(4, 3),(5, 4),
	(6, 1),(7, 2),(8, 4),(9, 1),(10, 2),
	(11, 5),(12, 3),(13, 2),(14, 4),(15, 5),
	(16, 1),(17, 2),(18, 3),(19, 4),(20, 2);